### ISSUE TITLE
Add Executable Location Type

### ISSUE THREAD

**Issue by MilesBreslin** [MilesBreslin/Chunky-Bits#8]
A location type that allows for running a shell command. On chunk fetch, the shell command would be called using `/bin/sh -c "$CMD"`, where `$CMD` is a part of the location field and write on `stdout` the full chunk.  On chunk write, the shell command would take in the chunk data on `stdin` with the hash of the file on argument 1 and output on `stdout` a command to be run by `/bin/sh -c "$CMD"`.

There may be a feature flag later to disable this at compile time as a security feature.

File Reference Example: 
```yaml
length: 52428800
parts:
  - data:
      - sha256: 4d589118cd5b236df24f79f951df8c4907098b19e25f45ffea3882d6ddcc2f37
        locations:
          - exec: "myexecutable SOMEFILE"
      - ...
    parity:
      - sha256: 1b9acb5b2436dfa1cff8bb0ad39b317c14c8d07214a5a437275d617352ded59b
        locations:
          - tmpdir/repo4/1b9acb5b2436dfa1cff8bb0ad39b317c14c8d07214a5a437275d617352ded59b
      - ...
  - ...
```

Cluster Reference Example:
```yaml
destinations:
  - location: ./tmpdir/repo
  - location: exec: "myexecutable"
...
```
